/*
 * terrain_classifier.h
 * AUTO-GENERATED by mujoco_to_firmware.py -- do not edit by hand.
 *
 * Decision tree trained on MuJoCo rigid-body physics rollouts.
 * 340 training windows  5-fold CV accuracy 77.1% +/- 11.2%
 * Features: std, rms, p2p, zcr, speed  (same formulas as terrain_sim.py)
 *
 * Usage in rover_firmware.ino:
 *   #include "terrain_classifier.h"
 *   String label = classifyTerrain();
 *   float  conf  = g_last_confidence;
 */

#pragma once
#include <math.h>

// Confidence of the last classifyTerrain() call (0.0-1.0).
float g_last_confidence = 0.0f;

// -- PWM -> speed calibration (fitted from MuJoCo rollouts) --------
// speed_ms = PWM_SPEED_SLOPE * currentPwm + PWM_SPEED_INTERCEPT
// RMSE: 0.0001 m/s
constexpr float PWM_SPEED_SLOPE     = 0.00147083f;
constexpr float PWM_SPEED_INTERCEPT = -0.00026536f;

inline float pwmToSpeed(int pwm) {
    float v = PWM_SPEED_SLOPE * (float)pwm + PWM_SPEED_INTERCEPT;
    return (v < 0.0f) ? 0.0f : v;
}

// -- Terrain driving profiles (from sim ADAPTIVE_POLICY) ------------
struct TerrainProfile {
    uint8_t maxPwm;
    float   accelRamp_s;
    float   turnGain;
};

// Ordered alphabetically: carpet, gravel, mat, tile
static const TerrainProfile TERRAIN_PROFILES[] = {
    {170, 0.40f, 0.80f},  // carpet
    {130, 0.60f, 0.60f},  // gravel
    {190, 0.30f, 0.90f},  // mat
    {220, 0.20f, 1.00f},  // tile
};
static const char* TERRAIN_NAMES[] = {"carpet", "gravel", "mat", "tile"};

// -- Extern declarations (defined in rover_firmware.ino) ------------
extern float feat_std;
extern float feat_rms;
extern float feat_p2p;
extern float feat_zcr;
extern float feat_speed;

// -- Decision tree (depth 5) -------------------------
inline String classifyTerrain() {
    if (feat_speed <= 0.304968f) {
        if (feat_p2p <= 3.965391f) {
            if (feat_speed <= 0.165180f) {
                if (feat_p2p <= 1.266122f) {
                    if (feat_speed <= 0.132214f) {
                        // leaf: gravel  conf=1.00  (0, 1, 0, 0)
                        g_last_confidence = 1.0000f;
                        return "gravel";
                    } else {
                        // leaf: carpet  conf=1.00  (1, 0, 0, 0)
                        g_last_confidence = 1.0000f;
                        return "carpet";
                    }
                } else {
                    // leaf: gravel  conf=1.00  (0, 1, 0, 0)
                    g_last_confidence = 1.0000f;
                    return "gravel";
                }
            } else {
                if (feat_rms <= 0.220056f) {
                    if (feat_speed <= 0.198398f) {
                        // leaf: mat  conf=0.53  (0, 0, 1, 0)
                        g_last_confidence = 0.5312f;
                        return "mat";
                    } else {
                        // leaf: tile  conf=0.69  (0, 0, 0, 1)
                        g_last_confidence = 0.6939f;
                        return "tile";
                    }
                } else {
                    if (feat_speed <= 0.301212f) {
                        // leaf: carpet  conf=0.57  (1, 0, 0, 0)
                        g_last_confidence = 0.5714f;
                        return "carpet";
                    } else {
                        // leaf: mat  conf=1.00  (0, 0, 1, 0)
                        g_last_confidence = 1.0000f;
                        return "mat";
                    }
                }
            }
        } else {
            if (feat_speed <= 0.257006f) {
                if (feat_zcr <= 52.500000f) {
                    // leaf: gravel  conf=1.00  (0, 1, 0, 0)
                    g_last_confidence = 1.0000f;
                    return "gravel";
                } else {
                    if (feat_rms <= 0.642081f) {
                        // leaf: gravel  conf=1.00  (0, 1, 0, 0)
                        g_last_confidence = 1.0000f;
                        return "gravel";
                    } else {
                        // leaf: carpet  conf=0.50  (0, 0, 0, 0)
                        g_last_confidence = 0.5000f;
                        return "carpet";
                    }
                }
            } else {
                // leaf: carpet  conf=1.00  (1, 0, 0, 0)
                g_last_confidence = 1.0000f;
                return "carpet";
            }
        }
    } else {
        if (feat_speed <= 0.338034f) {
            if (feat_speed <= 0.319662f) {
                // leaf: tile  conf=1.00  (0, 0, 0, 1)
                g_last_confidence = 1.0000f;
                return "tile";
            } else {
                // leaf: mat  conf=1.00  (0, 0, 1, 0)
                g_last_confidence = 1.0000f;
                return "mat";
            }
        } else {
            // leaf: tile  conf=1.00  (0, 0, 0, 1)
            g_last_confidence = 1.0000f;
            return "tile";
        }
    }
}
